[launcher]
author = UnshakeableSalt

[package]
id = placeholder_app

[ui]
is_visible = 1
label = Placeholder App

[app]
build = 1
description = Template Splunk App — replace with your app description
version = 0.1.0
