[notable_to_perplexity_json]
search = index=cim_modactions sourcetype=modular_alerts:notable_to_perplexity_json

[notable_to_slack_json]
search = index=cim_modactions sourcetype=modular_alerts:notable_to_slack_json
